drop table if exists member CASCADE;
//테이블 생성
 create table member
 (
        id   bigint generated by default as identity,
       name varchar(255),
       primary key (id)
  );

//insert
insert into member(name) values('spring2');
